import java.util.HashSet;
import java.util.Set;

public class SubjectTranslation {

    protected String original;
    protected Set<String> subjects_rus = new HashSet<>();
    protected Set<String> subjects_eng = new HashSet<>();


  public SubjectTranslation(String original) {
        this.original = original;
    }

    String originalTranscript1 = "Философия + Биоэтика + Психология и педагогика + Правоведение + История Отечества + История медицины + Экономика + Иностранный язык + Латинский язык + Физика, математика + Медицинская информатика + Химия + Биология + Биологическая химия, биохимия полости рта + Анатомия человека + Гистология, эмбриология и цитология + Нормальная физиология + Фармакология + Микробиология, вирусология, микробиология полости рта + Иммунология, клиническая иммунология + Патофизиология, патофизиология головы и шеи + Патологическая анатомия, патологическая анатомия головы и шеи + Эпидемиология + Гигиена + Общественное здоровье и здравоохранение, экономика здравоохранения + Пропедевтика внутренних болезней, внутренние болезни, клиническая фармакология + Хирургические болезни, общая хирургия + Лучевая диагностика + Безопасность жизнедеятельности + Инфекционные болезни, фтизиатрия + Медицинская реабилитация + Неврология + Оториноларингология + Офтальмология + Акушерство и гинекология + Педиатрия + Стоматологическое материаловедение + Стоматология профилактическая + Стоматология пропедевтическая + Кариесология и заболевание твердых тканей зубов + Эндодонтия + Пародонтология + Стоматологическая радиология + Стоматология терапевтическая, геронтостоматология + Стоматология хирургическая, анестезиология в стоматологии + Стоматология ортопедическая, гнатология + Стоматология клиническая + Этика, право и менеджмент в стоматологии + Зубопротезирование, протезирование зубных рядов и полном отсутствии зубов + Челюстно-лицевая хирургия + Детская стоматология + Медицинская генетика + Ортодонтия + Физическая культура + Иностранный язык в медицинской практике + Топографическая анатомия и оперативная хирургия + Нормальная физиология-физиология челюстно-лицевой области + Регенеративная медицина + Детская челюстно-лицевая хирургия + Психиатрия и наркология + Судебная медицина + Имплантология и реконструктивная хирургия полости рта + Дерматовенерология + Иностранный язык в биомедицинских исследованиях + Нано- и клеточные технологии в биологии и медицине + Методы физиологических исследований + Современная эндодонтия + Челюстно-лицевая косметология + Анестезиология и реаниматология";
    String translatedTranscript1 = "Philosophy + Bioethics + Psychology and pedagogy + Law + National history + History of medicine + Economics + Foreign language + Latin language + Physics and mathematics + Medical informatics + Chemistry + Biology + Biological chemistry, oral biochemistry + Human anatomy + Histology, embryology and cytology + Normal physiology + Pharmacology + Microbiology, virology, oral microbiology + Immunology, clinical immunology + Pathophysiology, head and neck pathophysiology + Pathological anatomy, pathological anatomy of head and neck + Epidemiology + Hygiene + Public health and healthcare, public health economics + Propaedeutics of internal diseases, internal diseases, clinical pharmacology + Surgical diseases, general surgery + Radiological diagnostics + Life safety + Infectious diseases, phthisiology + Medical rehabilitation + Neurology + Otorhinolaryngology + Ophthalmology + Obstetrics and gynecology + Pediatrics + Dental material science + Preventive dentistry + Propaedectectic Dentistry + Cariesology and dental hard tissue disease + Endodontics + Periodontics + Dental radiology + Therapeutic dentistry, gerontostomatology + Oral surgery, anesthesiology in dentistry + Prosthodontics, gnathology + Clinical dentistry + Ethics, law and management in dentistry + Dentistry, prosthetics of dental rows and full absence of teeth + Maxillofacial surgery + Pediatric dentistry + Medical genetics + Orthodontics + Physical therapy + Foreign language in medical practice + Topographic anatomy and operative surgery + Normal physiology-physiology of maxillofacial area + Regenerative medicine + Pediatric maxillofacial surgery + Psychiatry and narcology + Forensic medicine + Implantology and reconstructive oral surgery + Dermatovenerology + Foreign language in biomedical research + Nano- and cellular technologies in biology and medicine + Physiological research methods + Modern endodontics + Maxillofacial cosmetology + Anesthesiology and intensive care";

    String originalTranscript2 = "Иностранный язык (английский) + Физическая культура + Отечественная история + Политология + Социология + Философия= Правоведение + Математика + Высшая математика + Теория вероятностей и математическая статистика + Социально-экономическая статистика + Таможенная статистика + Информатика + Концепция современного естествознания + Экономическая теория + Финансы, денежное обращение и кредит + Менеджмент + Экономический потенциал таможенной территории России + Мировая экономика и внешнеэкономическая деятельность + Экономика таможенного дела + Налоги и таможенные платежи + Валютное регулирование и валютный контроль + Теория государства и права + Гражданское право + Гражданский и арбитражный процесс + Административное право + Трудовое право + Таможенное право + Международное право + Уголовное право + Уголовный процесс + Управление в таможенных органах + Организация таможенного контроля товаров и транспортных средств + Товарная номенклатура внешнеэкономической деятельности + Таможенно-тарифное регулирование внешнеэкономической деятельности и таможенная стоимость + Таможенное делопроизводство + Безопасность жизнедеятельности + История таможенного дела и таможенной политики России + Товароведение и экспертиза в таможенном деле + Культурология + Педагогика и психология + Экономика + Интернет технологии + Экономическая география + Экономико-математические методы + Информационные таможенные технологии + Конституционное право + Декларирование товаров и транспортных средств + Экология + Русский язык и культура речи + Природопользование + История предпринимательства + Управление персоналом + Финансовое право + Оффшорный бизнес + Организация валютного контроля в различных таможенных режимах + Таможенные платежи в различных таможенных режимах + Международные конвенции и соглашения по торговле + Внешнеторговая документация + Обоснование контрактных цен + Контракты в международной торговле + Практикум по контролю контрактных цен + Практикум по применению таможенных платежей + Практикум по применению экономико-математической модели + Экономическая безопасность + Теория и практика применения технических средств таможенного контроля + Торгово-экономические отношения России в современных условиях + Государственное регулирование экономики + Бизнес-планирование + Основы предпринимательства + Предпринимательское право + Валютное право + Информационно-библиотечная культура + Консенсусология + Здоровый образ жизни";
    String translatedTranscript2 = "Foreign language (English) + Physical education + National history + Political science + Sociology + Philosophy + Law + Mathematics + Higher mathematics + Probability theory and mathematical statistics + Social and economic statistics + Customs statistics + Computer science + Concepts of modern natural science + Economic theory + Finance, cash circulation and credit + Management + Economic potential of Russia's customs territory + World economics and foreign economic activity + Economics of customs + Taxes and customs payments + Currency regulation and currency control + Theory of state and law + Civil law + Civil and arbitrage process + Administrative law + Labor law + Customs law + International Law + Criminal law + Criminal process + Administration in customs bodies + Organization of customs control of goods and vehicles + Commodity nomenclature of foreign economic activity + Customs tariff regulation of foreign economic activities and customs value + Customs workflow + Life safety + History of Russian customs affairs and customs policy + Commodity science and examination in customs affairs + Culture studies + Pedagogy and psychology + Economics + Internet technologies + Economic geography + Economic and mathematical methods + Customs information technologies + Constitutional law + Goods and vehicles declaration + Ecology + Russian language and culture of speech + Nature management + History of entrepreneurship + Human resources management + Financial law + Offshore business + Organization of currency control in different customs regimes + Customs payments in different customs regimes + International conventions and agreements on trade + Foreign trade documentation + Justification of contract prices + Contracts in international trade + Workshop on control of contract prices + Workshop on application of customs fees + Workshop on application of economic and mathematical model + Economic security + Theory and practice of using technical means of customs control + Russian trade and economic relations in contemporary conditions + State regulation of economics + Business-planning + Fundamentals of entrepreneurship + Entrepreneurial law + Currency law + Information and library culture + Consensus science + Healthy lifestyle";

    String originalTranscript3 = "Деловой иностранный язык (английский) + Методология научных исследований в менеджменте + Проектное управление в отраслях экономики + Современный стратегический менеджмент + Управленческая экономика + Корпоративные финансы + Методология управления стратегическими проектами компании + Модели и механизмы стратегического корпоративного управления + Организационная теория и дизайн + Правовое обеспечение корпоративного управления + Технологии принятия и реализации корпоративных стратегических решений + Трансформационный менеджмент + Управление стоимостью компании (бизнеса) + Сетевой менеджмент + Стратегическое управление инвестициями + Управление стратегической реорганизацией + Цифровые технологии в управлении проектами";
    String translatedTranscript3 = "Business foreign language (English) + Scientific research methodology in management + Project management in industries of economy + Modern strategic management + Managerial economics + Corporate finance + Strategic project management methodology + Models and mechanisms of strategic corporate management + Organizational theory and design + Legal support of corporate management + Technologies of making and implementing corporate strategic decisions + Transformation management + Company (business) value management + Network management + Strategic investment management + Strategic realignment management + Digital technologies in project management";

    String originalTranscript4 = "Иностранный язык (английский) + Иностранный язык делового общения (английский) + Иностранный язык: профессиональные коммуникации (английский) + Физическая культура + Безопасность жизнедеятельности + Введение в политическую теорию: категории политической науки + История + История философии: классическая философия + Концепции современного естествознания + Политическая этика + Российская цивилизация: ценностное единство общества + Экология + Экономика, Политэкономия + Введение в политическую теорию: стратификационные, институциональные и неинституциональные основы политики + Введение в политическую теорию: теоретико-методологические основы политики + Высшая математика + Информатика + История философии: современная философия + Логика. Теория аргументации + Нормативное регулирование политических процессов + Основы риторики и коммуникации + Политическая история России и зарубежных стран + Политическая регионалистика + Политическая социология: концепции, методы, понятийный аппарат + Правоведение + Общий менеджмент + История политики и политических учений + Культурология + Политическая журналистика + Политические партии в России + Политическая психология + Политический анализ и прогнозирование: понятийный аппарат, концепции и теории + Политический менеджмент: понятийный аппарат, теории и концепты + Философия + Информационно-аналитическое обеспечение политического процесса + Политико-административное управление зарубежных стран + Политическая коммуникация: теоретико-методологические основы + Политические основы публичной власти + Политический анализ и прогнозирование: методы моделирования политических процессов + Политический менеджмент: современные формы политико- технологического управления + Технологии политической коммуникации + Формирование имиджа политика в социальных сетях+ GR-менеджмент: зарубежная и российская практика + Информационные технологии профилактики радикализма + Международные отношения и мировая политика: основные теории и концепты + Современная российская политика: политические отношения и политический процесс + Сравнительная политология + Этнополитология + Государственная власть и политическое управление в России + Коррупция как фактор современной политики + Международные отношения и мировая политика + Политическая конфликтология + Политическая транзитология + Политический менеджмент: электоральный менеджмент + Современные избирательные системы и избирательный процесс + Основы научно-исследовательской деятельности + Расширение мегаполиса: положительный и отрицательный опыт + Социально-политические стратегии и технологии в местном самоуправлении";
    String translatedTranscript4 = "Foreign language (English) + Foreign language: business communication (English) + Foreign language: professional communications (English) + Physical education + Life safety + Introduction to political theory: categories of political science + History + History of philosophy: classical philosophy + Concepts of modern natural science + Political ethics + Russian civilization: value unity of the society + Ecology + Economics, political economy + Introduction to political theory: stratification, institutional and non-institutional fundamentals of politics + Introduction to political theory: theoretical and methodological fundamentals of politics + Advanced mathematics + Informatics + History of philosophy: modern philosophy + Logics. Theory of argumentation + Normative regulation of political processes + Fundamentals of rhetoric and communication + Political history of Russia and foreign countries + Political regional studies + Political sociology: concepts, methods, conceptual apparatus + Jurisprudence + General management + History of politics and political doctrines + Cultural studies + Political journalism + Political parties in Russia + Political psychology + Political analysis and forecasting: conceptual apparatus, concepts and theories + Political management: conceptual apparatus, theories and concepts + Philosophy + Information and analytical support of political process + Political and administrative management of foreign countries + Political communication: theoretical and methodological fundamentals + Political fundamentals of public authorities + Political analysis and forecasting: methods of political process modeling + Political management: contemporary forms of political and technological management + Technologies of political communication + Formation of politician's image in social networks + GR-management: foreign and Russian practice + Information technologies of radicalism prevention + International relations and world politics: main theories and concepts + Contemporary Russian politics: political relations and political process + Comparative political science + Ethnopolitology + State power and political governance in Russia + Corruption as a factor in contemporary politics + International relations and world politics + Political conflictology + Political transitology + Political management: electoral management + Modern electoral systems and electoral process + Fundamentals of research activities + Expansion of the megacity: positive and negative experiences + Socio-political strategies and technologies in local government";

    String originalTranscript5 = "";
    String translatedTranscript5 = "";

    String originalTranscript6 = "";
    String translatedTranscript6 = "";

    String originalTranscript7 = "";
    String translatedTranscript7 = "";

    String originalTranscript8 = "";
    String translatedTranscript8 = "";

    String originalTranscript9 = "";
    String translatedTranscript9 = "";

    String originalTranscript10 = "";
    String translatedTranscript10 = "";

    String originalTranscript11 = "";
    String translatedTranscript11 = "";





}
